### ISSUE TITLE
Bug: load and subscribe mishandle resolve when using discriminated unions with optional fields

### ISSUE THREAD

**Issue by nrainhart** [garden-co/classic-jazz#2639]
load & subscribe behave incorrectly when used with discriminated unions:

```typescript
const Person = co.map({
  name: z.string(),
});
const Dog = co.map({
  type: z.literal("dog"),
  owner: Person,
});
const Cat = co.map({
  type: z.literal("cat"),
});

const Pet = co.discriminatedUnion("type", [Dog, Cat]);

const dog = Dog.create({
  type: "dog",
  owner: Person.create({ name: "John Doe" }),
});
const loadedPet = await loadCoValue(anySchemaToCoSchema(Pet), dog.id, {
  resolve: { owner: true },
  loadAs: me,
});
if (loadedPet?.type === "dog") {
  loadedPet?.owner.name; // type error: Property 'name' does not exist on type 'never'
}

const cat = Cat.create({
    type: "cat",
  });
  const loadedPet = await Pet.load(cat.id, {
    resolve: { owner: true },
    loadAs: me,
  });
  console.log({ loadedPet }); // { loadedPet: null }
  // The ref owner requested on ZCoMap is not defined in the schema from co_z3pg5wqtbMunzGv69ThqTp7efa5 on path owner
```

I expect either resolve to support owner in both cases (without generating type nor runtime errors), or owner not being included in resolve at all.

**Comment by nrainhart** [comment]
Note: revert 2475a465781f44c6c65500ce071694c03384237e once resolve works properly

**Comment by nrainhart** [comment]
See also https://github.com/garden-co/jazz/pull/2656

**Comment by nrainhart** [comment]
Anselm: for ensure loaded and subscribe, can we offer a specific overload / resolve shape on Discriminated Union that looks like `{ resolve: { discr1: resolveQuery1, discr2: resolveQuery2 } }`?

Nico: Personally, I feel like that goes against the discriminated union idea of only working with fields that are common between all union members until you make a type assertion, but happy to discuss it

Guido: I would put it in a special keyword, just to make more clear that we are resolving a union.
Something like:
```
{ resolve: { $switch: { discr1: resolveQuery1, discr2: resolveQuery2 } } }
```
